### ISSUE TITLE
Empty files not working

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#123]
Empty modules cause an exception when evaluated, because of an invocation of the head method on an empty lists. [source](https://github.com/rexim/Morganey/blob/master/src/main/scala/me/rexim/morganey/interpreter/MorganeyInterpreter.scala#L65).
## 

Steps to reproduce the error:
- Create a empty module in the `std/` directory
  - Alternative: Create a module only containing comments in the `std/` directory
- Fire up a repl session
- Load the newly created module
## 

observed behaviour:

```
\> load emptyTest
head of empty list
```

expected behaviour:

```
\> load emptyTest
load emptyTest
```
## 

This bug blocks the implementation of #67 (PR #122).

**Comment by rexim** [comment]
Full stacktrace:

```
java.util.NoSuchElementException: head of empty list
    at scala.collection.immutable.Nil$.head(List.scala:420)
    at scala.collection.immutable.Nil$.head(List.scala:417)
    at me.rexim.morganey.interpreter.MorganeyInterpreter$.computations$lzycompute$1(MorganeyInterpreter.scala:65)
    at me.rexim.morganey.interpreter.MorganeyInterpreter$.me$rexim$morganey$interpreter$MorganeyInterpreter$$computations$1(MorganeyInterpreter.scala:65)
    at me.rexim.morganey.interpreter.MorganeyInterpreter$.evalNodesComputation(MorganeyInterpreter.scala:68)
    at me.rexim.morganey.interpreter.MorganeyInterpreter$.loadFile(MorganeyInterpreter.scala:36)
    at me.rexim.morganey.interpreter.MorganeyInterpreter$.evalOneNodeComputation(MorganeyInterpreter.scala:54)
    at me.rexim.morganey.Main$$anonfun$2.apply(Main.scala:49)
    at me.rexim.morganey.Main$$anonfun$2.apply(Main.scala:48)
    at scala.util.Success.flatMap(Try.scala:231)
    at me.rexim.morganey.Main$.handleLine(Main.scala:48)
    at me.rexim.morganey.Main$$anonfun$3.apply(Main.scala:75)
    at me.rexim.morganey.Main$$anonfun$3.apply(Main.scala:75)
    at me.rexim.morganey.Main$.startRepl(Main.scala:81)
    at me.rexim.morganey.Main$.main(Main.scala:115)
    at me.rexim.morganey.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sbt.Run.invokeMain(Run.scala:67)
    at sbt.Run.run0(Run.scala:61)
    at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
    at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Logger$$anon$4.apply(Logger.scala:85)
    at sbt.TrapExit$App.run(TrapExit.scala:248)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by rexim** [comment]
lol, let me take this one. This is such a stupid mistake from my side! Thanks for filing a ticket for it! :)
