### ISSUE TITLE
How to run Morganey without sbt

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/Morganey#208]
For my plugin i need a command from which I can run the Morganey interpreter without running sbt. 

For Example
`morganey run "file.morg`

Does any such command exist in Morganey as i require something like this to implement the IDEA run configurations?

Thanks for your assistance

**Comment by 06needhamt** [comment]
I tried the following but it didn't work it just exits immediately 
![capture](https://cloud.githubusercontent.com/assets/4162227/18667694/95860ce2-7f29-11e6-90be-38b946e9f888.PNG)

**Comment by 06needhamt** [comment]
I've fixed this issue but mow i get this stacktrace 

```
"C:\Program Files\Java\jdk1.8.0_101\bin\java" -Dfile.encoding=windows-1252 -jar D:\GitHub\morganey-intellij-plugin\lib\morganey_2.11-0.0.1-SNAPSHOT.jar test.morg
java.lang.NoClassDefFoundError: scala/Product
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
    at java.lang.Class.getMethod0(Class.java:3018)
    at java.lang.Class.getMethod(Class.java:1784)
    at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: scala.Product
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 19 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
Process finished with exit code 1
```

**Comment by 06needhamt** [comment]
And i'm invoking Morganey like this

![capture 2](https://cloud.githubusercontent.com/assets/4162227/18668128/9584ce02-7f2b-11e6-8686-f288af442ec4.PNG)

**Comment by rexim** [comment]
The error https://github.com/morganey-lang/Morganey/issues/208#issuecomment-248271850 is a sign that the Scala runtime is not available in your environment. It's possible to build a "fat jar" of morganey that is selfcontained and includes all of the required runtime dependencies. But this fatjar build is not merged to the master at the moment. It's in this PR #203. I'll separate fatjar configuration from #203 and post it as a separate PR, because #203 requires so work to do and won't be merged soon.

**Comment by rexim** [comment]
Also, is it possible to access class `me.rexim.morganey.Main` from the plugin code? It's an entry point of the morganey interpreter and I believe it's present in one of the jars. Maybe it's possible to invoke `me.rexim.morganey.Main.main(Array("morganey.mgn"))` directly from the plugin? Not sure if that's the case. Just sharing my thoughts. :)

**Comment by 06needhamt** [comment]
Ok i guess i am going to have to wait until that is merged before i can run Morganey from within IntelliJ. Let me know when it is merged

**Comment by rexim** [comment]
> Let me know when it is merged

Sure. It should not be difficult. I'm gonna create the PR in 1-2 hours. I'll ping you. :)

**Comment by rexim** [comment]
@06needhamt Actually, it's quite simple. Add the following line

```
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")
```

to the `<morganey>/project/plugins.sbt` (make sure that all of the lines in the file are separated by newlines). Then at the root of the project just do

```
$ sbt assembly
```

and find fatjar at `<morganey>/target/scala-2.11/morganey-assembly-0.0.1-SNAPSHOT.jar`. Hope it helps. The proper configuration requires more stuff, but that's enough to just create a fatjar. The configuration is gonna be in the master soon.

**Comment by rexim** [comment]
@06needhamt the configuration is in the master. Please find the instructions on building uberjar at https://github.com/morganey-lang/Morganey#build-an-uberjar and close the question if everything's ok. Thanks!

**Comment by keddelzz** [comment]
@06needhamt Please don't forget to close this issue, if the question was answered to your satisfaction.

**Comment by 06needhamt** [comment]
@keddelzz Sorry
